//Maya ASCII 2026 scene
//Name: Huntsman_Asset5.ma
//Last modified: Fri, Dec 05, 2025 03:41:18 PM
//Codeset: 1252
requires maya "2026";
requires "stereoCamera" "10.0";
requires "mtoa" "5.5.3";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2026";
fileInfo "version" "2026";
fileInfo "cutIdentifier" "202507081222-4d6919b75c";
fileInfo "osv" "Windows 11 Enterprise v2009 (Build: 26100)";
fileInfo "UUID" "31E74096-464A-6FDD-5718-B1A8196C5138";
createNode transform -s -n "persp";
	rename -uid "3C9F25D3-446C-72D9-7C4E-1AB95B2A0347";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 29.926417004492983 30.238367466006817 61.905766910523099 ;
	setAttr ".r" -type "double3" -23.738352729605168 25.800000000002544 0 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "62EC2534-484D-D9D9-E81E-E880906707C0";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 75.11506692078521;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "A183160E-4A45-741E-3FE6-E4922CAE4C2A";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -90 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "DEA7C9D1-4100-6F1D-D3FC-859DC889B683";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "front";
	rename -uid "68678CE5-4FBB-8C63-A2B4-0CACF69D2DB7";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "18B1C591-4835-F007-9A97-F7A932F0B92A";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "side";
	rename -uid "E072BFD3-446E-A223-636D-3E8DA198215B";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 90 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "BBD320E7-48A8-F044-54A2-19827616D713";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -n "GrassyHillTerrain";
	rename -uid "E5F91619-4627-C116-F54D-0A82DE47278A";
	setAttr ".s" -type "double3" 1 0.5 1 ;
createNode mesh -n "GrassyHillTerrainShape" -p "GrassyHillTerrain";
	rename -uid "1A8F9249-45D9-F3A2-38C0-E38033A8B428";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".pv" -type "double2" 0.57499980926513672 0.44999980926513672 ;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Ambient+Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "1CD957E8-4F3D-EE7F-672E-648F9D55F8AF";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "61B60859-41A0-40D2-968D-EE9953DDB5F7";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "2428BA21-442B-9C5B-AF5A-958B6E498122";
createNode displayLayerManager -n "layerManager";
	rename -uid "84CAFEAF-43C8-4EE9-2773-E7BFA8D77794";
createNode displayLayer -n "defaultLayer";
	rename -uid "257FDBF7-407B-15C9-4BF0-73A143C29B1A";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "E55F4140-42E7-FBFB-8FEC-3A824C30D6F8";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "BA1F3A7B-4B46-3C00-D78C-C79E2860DB04";
	setAttr ".g" yes;
createNode script -n "uiConfigurationScriptNode";
	rename -uid "8438F64C-42E9-D80E-8F0F-F5BD24D597E8";
	setAttr ".b" -type "string" (
		"// Maya Mel UI Configuration File.\n//\n//  This script is machine generated.  Edit at your own risk.\n//\n//\n\nglobal string $gMainPane;\nif (`paneLayout -exists $gMainPane`) {\n\n\tglobal int $gUseScenePanelConfig;\n\tint    $useSceneConfig = $gUseScenePanelConfig;\n\tint    $nodeEditorPanelVisible = stringArrayContains(\"nodeEditorPanel1\", `getPanel -vis`);\n\tint    $nodeEditorWorkspaceControlOpen = (`workspaceControl -exists nodeEditorPanel1Window` && `workspaceControl -q -visible nodeEditorPanel1Window`);\n\tint    $menusOkayInPanels = `optionVar -q allowMenusInPanels`;\n\tint    $nVisPanes = `paneLayout -q -nvp $gMainPane`;\n\tint    $nPanes = 0;\n\tstring $editorName;\n\tstring $panelName;\n\tstring $itemFilterName;\n\tstring $panelConfig;\n\n\t//\n\t//  get current state of the UI\n\t//\n\tsceneUIReplacement -update $gMainPane;\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Top View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Top View\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|top\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 16384\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n"
		+ "            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n"
		+ "            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -bluePencil 1\n            -greasePencils 0\n            -excludeObjectPreset \"All\" \n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Side View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Side View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|side\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n"
		+ "            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 16384\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n"
		+ "            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -bluePencil 1\n            -greasePencils 0\n            -excludeObjectPreset \"All\" \n"
		+ "            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Front View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Front View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|front\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n"
		+ "            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 16384\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n"
		+ "            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n"
		+ "            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -bluePencil 1\n            -greasePencils 0\n            -excludeObjectPreset \"All\" \n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Persp View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Persp View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n"
		+ "            -camera \"|persp\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 16384\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n"
		+ "            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n"
		+ "            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -bluePencil 1\n            -greasePencils 0\n            -excludeObjectPreset \"All\" \n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1317\n            -height 706\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n"
		+ "\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"outlinerPanel\" (localizedPanelLabel(\"ToggledOutliner\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\toutlinerPanel -edit -l (localizedPanelLabel(\"ToggledOutliner\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        outlinerEditor -e \n            -docTag \"isolOutln_fromSeln\" \n            -showShapes 0\n            -showAssignedMaterials 0\n            -showTimeEditor 1\n            -showReferenceNodes 1\n            -showReferenceMembers 1\n            -showAttributes 0\n            -showConnected 0\n            -showAnimCurvesOnly 0\n            -showMuteInfo 0\n            -organizeByLayer 1\n            -organizeByClip 1\n            -showAnimLayerWeight 1\n            -autoExpandLayers 1\n            -autoExpand 0\n            -showDagOnly 1\n            -showAssets 1\n            -showContainedOnly 1\n            -showPublishedAsConnected 0\n            -showParentContainers 0\n            -showContainerContents 1\n"
		+ "            -ignoreDagHierarchy 0\n            -expandConnections 0\n            -showUpstreamCurves 1\n            -showUnitlessCurves 1\n            -showCompounds 1\n            -showLeafs 1\n            -showNumericAttrsOnly 0\n            -highlightActive 1\n            -autoSelectNewObjects 0\n            -doNotSelectNewObjects 0\n            -dropIsParent 1\n            -transmitFilters 0\n            -setFilter \"defaultSetFilter\" \n            -showSetMembers 1\n            -allowMultiSelection 1\n            -alwaysToggleSelect 0\n            -directSelect 0\n            -isSet 0\n            -isSetMember 0\n            -showUfeItems 1\n            -displayMode \"DAG\" \n            -expandObjects 0\n            -setsIgnoreFilters 1\n            -containersIgnoreFilters 0\n            -editAttrName 0\n            -showAttrValues 0\n            -highlightSecondary 0\n            -showUVAttrsOnly 0\n            -showTextureNodesOnly 0\n            -attrAlphaOrder \"default\" \n            -animLayerFilterOptions \"allAffecting\" \n            -sortOrder \"none\" \n"
		+ "            -longNames 0\n            -niceNames 1\n            -selectCommand \"print(\\\"\\\")\" \n            -showNamespace 1\n            -showPinIcons 0\n            -mapMotionTrails 0\n            -ignoreHiddenAttribute 0\n            -ignoreOutlinerColor 0\n            -renderFilterVisible 0\n            -renderFilterIndex 0\n            -selectionOrder \"chronological\" \n            -expandAttribute 0\n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"outlinerPanel\" (localizedPanelLabel(\"Outliner\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\toutlinerPanel -edit -l (localizedPanelLabel(\"Outliner\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        outlinerEditor -e \n            -showShapes 0\n            -showAssignedMaterials 0\n            -showTimeEditor 1\n            -showReferenceNodes 0\n            -showReferenceMembers 0\n            -showAttributes 0\n            -showConnected 0\n"
		+ "            -showAnimCurvesOnly 0\n            -showMuteInfo 0\n            -organizeByLayer 1\n            -organizeByClip 1\n            -showAnimLayerWeight 1\n            -autoExpandLayers 1\n            -autoExpand 0\n            -showDagOnly 1\n            -showAssets 1\n            -showContainedOnly 1\n            -showPublishedAsConnected 0\n            -showParentContainers 0\n            -showContainerContents 1\n            -ignoreDagHierarchy 0\n            -expandConnections 0\n            -showUpstreamCurves 1\n            -showUnitlessCurves 1\n            -showCompounds 1\n            -showLeafs 1\n            -showNumericAttrsOnly 0\n            -highlightActive 1\n            -autoSelectNewObjects 0\n            -doNotSelectNewObjects 0\n            -dropIsParent 1\n            -transmitFilters 0\n            -setFilter \"defaultSetFilter\" \n            -showSetMembers 1\n            -allowMultiSelection 1\n            -alwaysToggleSelect 0\n            -directSelect 0\n            -showUfeItems 1\n            -displayMode \"DAG\" \n"
		+ "            -expandObjects 0\n            -setsIgnoreFilters 1\n            -containersIgnoreFilters 0\n            -editAttrName 0\n            -showAttrValues 0\n            -highlightSecondary 0\n            -showUVAttrsOnly 0\n            -showTextureNodesOnly 0\n            -attrAlphaOrder \"default\" \n            -animLayerFilterOptions \"allAffecting\" \n            -sortOrder \"none\" \n            -longNames 0\n            -niceNames 1\n            -showNamespace 1\n            -showPinIcons 0\n            -mapMotionTrails 0\n            -ignoreHiddenAttribute 0\n            -ignoreOutlinerColor 0\n            -renderFilterVisible 0\n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"graphEditor\" (localizedPanelLabel(\"Graph Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Graph Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"OutlineEd\");\n"
		+ "            outlinerEditor -e \n                -showShapes 1\n                -showAssignedMaterials 0\n                -showTimeEditor 1\n                -showReferenceNodes 0\n                -showReferenceMembers 0\n                -showAttributes 1\n                -showConnected 1\n                -showAnimCurvesOnly 1\n                -showMuteInfo 0\n                -organizeByLayer 1\n                -organizeByClip 1\n                -showAnimLayerWeight 1\n                -autoExpandLayers 1\n                -autoExpand 1\n                -showDagOnly 0\n                -showAssets 1\n                -showContainedOnly 0\n                -showPublishedAsConnected 0\n                -showParentContainers 0\n                -showContainerContents 0\n                -ignoreDagHierarchy 0\n                -expandConnections 1\n                -showUpstreamCurves 1\n                -showUnitlessCurves 1\n                -showCompounds 0\n                -showLeafs 1\n                -showNumericAttrsOnly 1\n                -highlightActive 0\n"
		+ "                -autoSelectNewObjects 1\n                -doNotSelectNewObjects 0\n                -dropIsParent 1\n                -transmitFilters 1\n                -setFilter \"0\" \n                -showSetMembers 0\n                -allowMultiSelection 1\n                -alwaysToggleSelect 0\n                -directSelect 0\n                -showUfeItems 1\n                -displayMode \"DAG\" \n                -expandObjects 0\n                -setsIgnoreFilters 1\n                -containersIgnoreFilters 0\n                -editAttrName 0\n                -showAttrValues 0\n                -highlightSecondary 0\n                -showUVAttrsOnly 0\n                -showTextureNodesOnly 0\n                -attrAlphaOrder \"default\" \n                -animLayerFilterOptions \"allAffecting\" \n                -sortOrder \"none\" \n                -longNames 0\n                -niceNames 1\n                -showNamespace 1\n                -showPinIcons 1\n                -mapMotionTrails 1\n                -ignoreHiddenAttribute 0\n                -ignoreOutlinerColor 0\n"
		+ "                -renderFilterVisible 0\n                $editorName;\n\n\t\t\t$editorName = ($panelName+\"GraphEd\");\n            animCurveEditor -e \n                -displayValues 0\n                -snapTime \"integer\" \n                -snapValue \"none\" \n                -showPlayRangeShades \"on\" \n                -lockPlayRangeShades \"off\" \n                -smoothness \"fine\" \n                -resultSamples 1\n                -resultScreenSamples 0\n                -resultUpdate \"delayed\" \n                -showUpstreamCurves 1\n                -tangentScale 1\n                -tangentLineThickness 1\n                -keyMinScale 1\n                -stackedCurvesMin -1\n                -stackedCurvesMax 1\n                -stackedCurvesSpace 0.2\n                -preSelectionHighlight 0\n                -limitToSelectedCurves 0\n                -constrainDrag 0\n                -valueLinesToggle 0\n                -highlightAffectedCurves 0\n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n"
		+ "\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dopeSheetPanel\" (localizedPanelLabel(\"Dope Sheet\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Dope Sheet\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"OutlineEd\");\n            outlinerEditor -e \n                -showShapes 1\n                -showAssignedMaterials 0\n                -showTimeEditor 1\n                -showReferenceNodes 0\n                -showReferenceMembers 0\n                -showAttributes 1\n                -showConnected 1\n                -showAnimCurvesOnly 1\n                -showMuteInfo 0\n                -organizeByLayer 1\n                -organizeByClip 1\n                -showAnimLayerWeight 1\n                -autoExpandLayers 1\n                -autoExpand 1\n                -showDagOnly 0\n                -showAssets 1\n                -showContainedOnly 0\n                -showPublishedAsConnected 0\n                -showParentContainers 0\n"
		+ "                -showContainerContents 0\n                -ignoreDagHierarchy 0\n                -expandConnections 1\n                -showUpstreamCurves 1\n                -showUnitlessCurves 0\n                -showCompounds 0\n                -showLeafs 1\n                -showNumericAttrsOnly 1\n                -highlightActive 0\n                -autoSelectNewObjects 0\n                -doNotSelectNewObjects 1\n                -dropIsParent 1\n                -transmitFilters 0\n                -setFilter \"0\" \n                -showSetMembers 1\n                -allowMultiSelection 1\n                -alwaysToggleSelect 0\n                -directSelect 0\n                -showUfeItems 1\n                -displayMode \"DAG\" \n                -expandObjects 0\n                -setsIgnoreFilters 1\n                -containersIgnoreFilters 0\n                -editAttrName 0\n                -showAttrValues 0\n                -highlightSecondary 0\n                -showUVAttrsOnly 0\n                -showTextureNodesOnly 0\n                -attrAlphaOrder \"default\" \n"
		+ "                -animLayerFilterOptions \"allAffecting\" \n                -sortOrder \"none\" \n                -longNames 0\n                -niceNames 1\n                -showNamespace 1\n                -showPinIcons 0\n                -mapMotionTrails 1\n                -ignoreHiddenAttribute 0\n                -ignoreOutlinerColor 0\n                -renderFilterVisible 0\n                $editorName;\n\n\t\t\t$editorName = ($panelName+\"DopeSheetEd\");\n            dopeSheetEditor -e \n                -displayValues 0\n                -snapTime \"none\" \n                -snapValue \"none\" \n                -outliner \"dopeSheetPanel1OutlineEd\" \n                -hierarchyBelow 0\n                -selectionWindow 0 0 0 0 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"timeEditorPanel\" (localizedPanelLabel(\"Time Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Time Editor\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"clipEditorPanel\" (localizedPanelLabel(\"Trax Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Trax Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = clipEditorNameFromPanel($panelName);\n            clipEditor -e \n                -displayValues 0\n                -snapTime \"none\" \n                -snapValue \"none\" \n                -initialized 0\n                -manageSequencer 0 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"sequenceEditorPanel\" (localizedPanelLabel(\"Camera Sequencer\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Camera Sequencer\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = sequenceEditorNameFromPanel($panelName);\n"
		+ "            clipEditor -e \n                -displayValues 0\n                -snapTime \"none\" \n                -snapValue \"none\" \n                -initialized 0\n                -manageSequencer 1 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"hyperGraphPanel\" (localizedPanelLabel(\"Hypergraph Hierarchy\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Hypergraph Hierarchy\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"HyperGraphEd\");\n            hyperGraph -e \n                -graphLayoutStyle \"hierarchicalLayout\" \n                -orientation \"horiz\" \n                -mergeConnections 0\n                -zoom 1\n                -animateTransition 0\n                -showRelationships 1\n                -showShapes 0\n                -showDeformers 0\n                -showExpressions 0\n                -showConstraints 0\n"
		+ "                -showConnectionFromSelected 0\n                -showConnectionToSelected 0\n                -showConstraintLabels 0\n                -showUnderworld 0\n                -showInvisible 0\n                -transitionFrames 1\n                -opaqueContainers 0\n                -freeform 0\n                -imagePosition 0 0 \n                -imageScale 1\n                -imageEnabled 0\n                -graphType \"DAG\" \n                -heatMapDisplay 0\n                -updateSelection 1\n                -updateNodeAdded 1\n                -useDrawOverrideColor 0\n                -limitGraphTraversal -1\n                -range 0 0 \n                -iconSize \"smallIcons\" \n                -showCachedConnections 0\n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"hyperShadePanel\" (localizedPanelLabel(\"Hypershade\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Hypershade\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"visorPanel\" (localizedPanelLabel(\"Visor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Visor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"nodeEditorPanel\" (localizedPanelLabel(\"Node Editor\")) `;\n\tif ($nodeEditorPanelVisible || $nodeEditorWorkspaceControlOpen) {\n\t\tif (\"\" == $panelName) {\n\t\t\tif ($useSceneConfig) {\n\t\t\t\t$panelName = `scriptedPanel -unParent  -type \"nodeEditorPanel\" -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels `;\n\n\t\t\t$editorName = ($panelName+\"NodeEditorEd\");\n            nodeEditor -e \n                -allAttributes 0\n                -allNodes 0\n                -autoSizeNodes 1\n                -consistentNameSize 1\n                -createNodeCommand \"nodeEdCreateNodeCommand\" \n"
		+ "                -connectNodeOnCreation 0\n                -connectOnDrop 0\n                -copyConnectionsOnPaste 0\n                -connectionStyle \"bezier\" \n                -defaultPinnedState 0\n                -additiveGraphingMode 0\n                -connectedGraphingMode 1\n                -settingsChangedCallback \"nodeEdSyncControls\" \n                -traversalDepthLimit -1\n                -keyPressCommand \"nodeEdKeyPressCommand\" \n                -nodeTitleMode \"name\" \n                -gridSnap 0\n                -gridVisibility 1\n                -crosshairOnEdgeDragging 0\n                -popupMenuScript \"nodeEdBuildPanelMenus\" \n                -showNamespace 1\n                -showShapes 1\n                -showSGShapes 0\n                -showTransforms 1\n                -useAssets 1\n                -syncedSelection 1\n                -extendToShapes 1\n                -showUnitConversions 0\n                -editorMode \"default\" \n                -hasWatchpoint 0\n                $editorName;\n\t\t\t}\n\t\t} else {\n\t\t\t$label = `panel -q -label $panelName`;\n"
		+ "\t\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"NodeEditorEd\");\n            nodeEditor -e \n                -allAttributes 0\n                -allNodes 0\n                -autoSizeNodes 1\n                -consistentNameSize 1\n                -createNodeCommand \"nodeEdCreateNodeCommand\" \n                -connectNodeOnCreation 0\n                -connectOnDrop 0\n                -copyConnectionsOnPaste 0\n                -connectionStyle \"bezier\" \n                -defaultPinnedState 0\n                -additiveGraphingMode 0\n                -connectedGraphingMode 1\n                -settingsChangedCallback \"nodeEdSyncControls\" \n                -traversalDepthLimit -1\n                -keyPressCommand \"nodeEdKeyPressCommand\" \n                -nodeTitleMode \"name\" \n                -gridSnap 0\n                -gridVisibility 1\n                -crosshairOnEdgeDragging 0\n                -popupMenuScript \"nodeEdBuildPanelMenus\" \n                -showNamespace 1\n"
		+ "                -showShapes 1\n                -showSGShapes 0\n                -showTransforms 1\n                -useAssets 1\n                -syncedSelection 1\n                -extendToShapes 1\n                -showUnitConversions 0\n                -editorMode \"default\" \n                -hasWatchpoint 0\n                $editorName;\n\t\t\tif (!$useSceneConfig) {\n\t\t\t\tpanel -e -l $label $panelName;\n\t\t\t}\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"createNodePanel\" (localizedPanelLabel(\"Create Node\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Create Node\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"polyTexturePlacementPanel\" (localizedPanelLabel(\"UV Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"UV Editor\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"renderWindowPanel\" (localizedPanelLabel(\"Render View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Render View\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"shapePanel\" (localizedPanelLabel(\"Shape Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tshapePanel -edit -l (localizedPanelLabel(\"Shape Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"posePanel\" (localizedPanelLabel(\"Pose Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tposePanel -edit -l (localizedPanelLabel(\"Pose Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n"
		+ "\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dynRelEdPanel\" (localizedPanelLabel(\"Dynamic Relationships\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Dynamic Relationships\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"relationshipPanel\" (localizedPanelLabel(\"Relationship Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Relationship Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"referenceEditorPanel\" (localizedPanelLabel(\"Reference Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Reference Editor\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dynPaintScriptedPanelType\" (localizedPanelLabel(\"Paint Effects\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Paint Effects\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"scriptEditorPanel\" (localizedPanelLabel(\"Script Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Script Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"profilerPanel\" (localizedPanelLabel(\"Profiler Tool\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Profiler Tool\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"contentBrowserPanel\" (localizedPanelLabel(\"Content Browser\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Content Browser\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"Stereo\" (localizedPanelLabel(\"Stereo\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Stereo\")) -mbv $menusOkayInPanels  $panelName;\n{ string $editorName = ($panelName+\"Editor\");\n            stereoCameraView -e \n                -camera \"|persp\" \n                -useInteractiveMode 0\n                -displayLights \"default\" \n                -displayAppearance \"wireframe\" \n                -activeOnly 0\n                -ignorePanZoom 0\n                -wireframeOnShaded 0\n"
		+ "                -headsUpDisplay 1\n                -holdOuts 1\n                -selectionHiliteDisplay 1\n                -useDefaultMaterial 0\n                -bufferMode \"double\" \n                -twoSidedLighting 1\n                -backfaceCulling 0\n                -xray 0\n                -jointXray 0\n                -activeComponentsXray 0\n                -displayTextures 0\n                -smoothWireframe 0\n                -lineWidth 1\n                -textureAnisotropic 0\n                -textureHilight 1\n                -textureSampling 2\n                -textureDisplay \"modulate\" \n                -textureMaxSize 16384\n                -fogging 0\n                -fogSource \"fragment\" \n                -fogMode \"linear\" \n                -fogStart 0\n                -fogEnd 100\n                -fogDensity 0.1\n                -fogColor 0.5 0.5 0.5 1 \n                -depthOfFieldPreview 1\n                -maxConstantTransparency 1\n                -objectFilterShowInHUD 1\n                -isFiltered 0\n                -colorResolution 4 4 \n"
		+ "                -bumpResolution 4 4 \n                -textureCompression 0\n                -transparencyAlgorithm \"frontAndBackCull\" \n                -transpInShadows 0\n                -cullingOverride \"none\" \n                -lowQualityLighting 0\n                -maximumNumHardwareLights 0\n                -occlusionCulling 0\n                -shadingModel 0\n                -useBaseRenderer 0\n                -useReducedRenderer 0\n                -smallObjectCulling 0\n                -smallObjectThreshold -1 \n                -interactiveDisableShadows 0\n                -interactiveBackFaceCull 0\n                -sortTransparent 1\n                -controllers 1\n                -nurbsCurves 1\n                -nurbsSurfaces 1\n                -polymeshes 1\n                -subdivSurfaces 1\n                -planes 1\n                -lights 1\n                -cameras 1\n                -controlVertices 1\n                -hulls 1\n                -grid 1\n                -imagePlane 1\n                -joints 1\n                -ikHandles 1\n"
		+ "                -deformers 1\n                -dynamics 1\n                -particleInstancers 1\n                -fluids 1\n                -hairSystems 1\n                -follicles 1\n                -nCloths 1\n                -nParticles 1\n                -nRigids 1\n                -dynamicConstraints 1\n                -locators 1\n                -manipulators 1\n                -pluginShapes 1\n                -dimensions 1\n                -handles 1\n                -pivots 1\n                -textures 1\n                -strokes 1\n                -motionTrails 1\n                -clipGhosts 1\n                -bluePencil 1\n                -greasePencils 0\n                -excludeObjectPreset \"All\" \n                -shadows 0\n                -captureSequenceNumber -1\n                -width 0\n                -height 0\n                -sceneRenderFilter 0\n                -displayMode \"centerEye\" \n                -viewColor 0 0 0 1 \n                -useCustomBackground 1\n                $editorName;\n            stereoCameraView -e -viewSelected 0 $editorName;\n"
		+ "            stereoCameraView -e \n                -pluginObjects \"gpuCacheDisplayFilter\" 1 \n                $editorName; };\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\tif ($useSceneConfig) {\n        string $configName = `getPanel -cwl (localizedPanelLabel(\"Current Layout\"))`;\n        if (\"\" != $configName) {\n\t\t\tpanelConfiguration -edit -label (localizedPanelLabel(\"Current Layout\")) \n\t\t\t\t-userCreated false\n\t\t\t\t-defaultImage \"vacantCell.xP:/\"\n\t\t\t\t-image \"\"\n\t\t\t\t-sc false\n\t\t\t\t-configString \"global string $gMainPane; paneLayout -e -cn \\\"single\\\" -ps 1 100 100 $gMainPane;\"\n\t\t\t\t-removeAllPanels\n\t\t\t\t-ap false\n\t\t\t\t\t(localizedPanelLabel(\"Persp View\")) \n\t\t\t\t\t\"modelPanel\"\n"
		+ "\t\t\t\t\t\"$panelName = `modelPanel -unParent -l (localizedPanelLabel(\\\"Persp View\\\")) -mbv $menusOkayInPanels `;\\n$editorName = $panelName;\\nmodelEditor -e \\n    -cam `findStartUpCamera persp` \\n    -useInteractiveMode 0\\n    -displayLights \\\"default\\\" \\n    -displayAppearance \\\"smoothShaded\\\" \\n    -activeOnly 0\\n    -ignorePanZoom 0\\n    -wireframeOnShaded 0\\n    -headsUpDisplay 1\\n    -holdOuts 1\\n    -selectionHiliteDisplay 1\\n    -useDefaultMaterial 0\\n    -bufferMode \\\"double\\\" \\n    -twoSidedLighting 0\\n    -backfaceCulling 0\\n    -xray 0\\n    -jointXray 0\\n    -activeComponentsXray 0\\n    -displayTextures 0\\n    -smoothWireframe 0\\n    -lineWidth 1\\n    -textureAnisotropic 0\\n    -textureHilight 1\\n    -textureSampling 2\\n    -textureDisplay \\\"modulate\\\" \\n    -textureMaxSize 16384\\n    -fogging 0\\n    -fogSource \\\"fragment\\\" \\n    -fogMode \\\"linear\\\" \\n    -fogStart 0\\n    -fogEnd 100\\n    -fogDensity 0.1\\n    -fogColor 0.5 0.5 0.5 1 \\n    -depthOfFieldPreview 1\\n    -maxConstantTransparency 1\\n    -rendererName \\\"vp2Renderer\\\" \\n    -objectFilterShowInHUD 1\\n    -isFiltered 0\\n    -colorResolution 256 256 \\n    -bumpResolution 512 512 \\n    -textureCompression 0\\n    -transparencyAlgorithm \\\"frontAndBackCull\\\" \\n    -transpInShadows 0\\n    -cullingOverride \\\"none\\\" \\n    -lowQualityLighting 0\\n    -maximumNumHardwareLights 1\\n    -occlusionCulling 0\\n    -shadingModel 0\\n    -useBaseRenderer 0\\n    -useReducedRenderer 0\\n    -smallObjectCulling 0\\n    -smallObjectThreshold -1 \\n    -interactiveDisableShadows 0\\n    -interactiveBackFaceCull 0\\n    -sortTransparent 1\\n    -controllers 1\\n    -nurbsCurves 1\\n    -nurbsSurfaces 1\\n    -polymeshes 1\\n    -subdivSurfaces 1\\n    -planes 1\\n    -lights 1\\n    -cameras 1\\n    -controlVertices 1\\n    -hulls 1\\n    -grid 1\\n    -imagePlane 1\\n    -joints 1\\n    -ikHandles 1\\n    -deformers 1\\n    -dynamics 1\\n    -particleInstancers 1\\n    -fluids 1\\n    -hairSystems 1\\n    -follicles 1\\n    -nCloths 1\\n    -nParticles 1\\n    -nRigids 1\\n    -dynamicConstraints 1\\n    -locators 1\\n    -manipulators 1\\n    -pluginShapes 1\\n    -dimensions 1\\n    -handles 1\\n    -pivots 1\\n    -textures 1\\n    -strokes 1\\n    -motionTrails 1\\n    -clipGhosts 1\\n    -bluePencil 1\\n    -greasePencils 0\\n    -excludeObjectPreset \\\"All\\\" \\n    -shadows 0\\n    -captureSequenceNumber -1\\n    -width 1317\\n    -height 706\\n    -sceneRenderFilter 0\\n    $editorName;\\nmodelEditor -e -viewSelected 0 $editorName;\\nmodelEditor -e \\n    -pluginObjects \\\"gpuCacheDisplayFilter\\\" 1 \\n    $editorName\"\n"
		+ "\t\t\t\t\t\"modelPanel -edit -l (localizedPanelLabel(\\\"Persp View\\\")) -mbv $menusOkayInPanels  $panelName;\\n$editorName = $panelName;\\nmodelEditor -e \\n    -cam `findStartUpCamera persp` \\n    -useInteractiveMode 0\\n    -displayLights \\\"default\\\" \\n    -displayAppearance \\\"smoothShaded\\\" \\n    -activeOnly 0\\n    -ignorePanZoom 0\\n    -wireframeOnShaded 0\\n    -headsUpDisplay 1\\n    -holdOuts 1\\n    -selectionHiliteDisplay 1\\n    -useDefaultMaterial 0\\n    -bufferMode \\\"double\\\" \\n    -twoSidedLighting 0\\n    -backfaceCulling 0\\n    -xray 0\\n    -jointXray 0\\n    -activeComponentsXray 0\\n    -displayTextures 0\\n    -smoothWireframe 0\\n    -lineWidth 1\\n    -textureAnisotropic 0\\n    -textureHilight 1\\n    -textureSampling 2\\n    -textureDisplay \\\"modulate\\\" \\n    -textureMaxSize 16384\\n    -fogging 0\\n    -fogSource \\\"fragment\\\" \\n    -fogMode \\\"linear\\\" \\n    -fogStart 0\\n    -fogEnd 100\\n    -fogDensity 0.1\\n    -fogColor 0.5 0.5 0.5 1 \\n    -depthOfFieldPreview 1\\n    -maxConstantTransparency 1\\n    -rendererName \\\"vp2Renderer\\\" \\n    -objectFilterShowInHUD 1\\n    -isFiltered 0\\n    -colorResolution 256 256 \\n    -bumpResolution 512 512 \\n    -textureCompression 0\\n    -transparencyAlgorithm \\\"frontAndBackCull\\\" \\n    -transpInShadows 0\\n    -cullingOverride \\\"none\\\" \\n    -lowQualityLighting 0\\n    -maximumNumHardwareLights 1\\n    -occlusionCulling 0\\n    -shadingModel 0\\n    -useBaseRenderer 0\\n    -useReducedRenderer 0\\n    -smallObjectCulling 0\\n    -smallObjectThreshold -1 \\n    -interactiveDisableShadows 0\\n    -interactiveBackFaceCull 0\\n    -sortTransparent 1\\n    -controllers 1\\n    -nurbsCurves 1\\n    -nurbsSurfaces 1\\n    -polymeshes 1\\n    -subdivSurfaces 1\\n    -planes 1\\n    -lights 1\\n    -cameras 1\\n    -controlVertices 1\\n    -hulls 1\\n    -grid 1\\n    -imagePlane 1\\n    -joints 1\\n    -ikHandles 1\\n    -deformers 1\\n    -dynamics 1\\n    -particleInstancers 1\\n    -fluids 1\\n    -hairSystems 1\\n    -follicles 1\\n    -nCloths 1\\n    -nParticles 1\\n    -nRigids 1\\n    -dynamicConstraints 1\\n    -locators 1\\n    -manipulators 1\\n    -pluginShapes 1\\n    -dimensions 1\\n    -handles 1\\n    -pivots 1\\n    -textures 1\\n    -strokes 1\\n    -motionTrails 1\\n    -clipGhosts 1\\n    -bluePencil 1\\n    -greasePencils 0\\n    -excludeObjectPreset \\\"All\\\" \\n    -shadows 0\\n    -captureSequenceNumber -1\\n    -width 1317\\n    -height 706\\n    -sceneRenderFilter 0\\n    $editorName;\\nmodelEditor -e -viewSelected 0 $editorName;\\nmodelEditor -e \\n    -pluginObjects \\\"gpuCacheDisplayFilter\\\" 1 \\n    $editorName\"\n"
		+ "\t\t\t\t$configName;\n\n            setNamedPanelLayout (localizedPanelLabel(\"Current Layout\"));\n        }\n\n        panelHistory -e -clear mainPanelHistory;\n        sceneUIReplacement -clear;\n\t}\n\n\ngrid -spacing 5 -size 12 -divisions 5 -displayAxes yes -displayGridLines yes -displayDivisionLines yes -displayPerspectiveLabels no -displayOrthographicLabels no -displayAxesBold yes -perspectiveLabelPosition axis -orthographicLabelPosition edge;\nviewManip -drawCompass 0 -compassAngle 0 -frontParameters \"\" -homeParameters \"\" -selectionLockParameters \"\";\n}\n");
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "8E0E1717-4044-5BE0-B2DC-359CCD0A67B0";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 200 ";
	setAttr ".st" 6;
createNode polyCube -n "polyCube1";
	rename -uid "B07F88ED-4053-8AAC-B6E5-AAADC234AEDD";
	setAttr ".w" 35;
	setAttr ".d" 35;
	setAttr ".sw" 30;
	setAttr ".sd" 30;
	setAttr ".cuv" 4;
createNode polyAutoProj -n "polyAutoProj1";
	rename -uid "7BBDFB61-40EE-48E6-2A4D-F2889073BA01";
	setAttr ".cch" yes;
	setAttr ".uopa" yes;
	setAttr ".ics" -type "componentList" 1 "f[0:1919]";
	setAttr ".ix" -type "matrix" 1 0 0 0 0 0.5 0 0 0 0 1 0 0 0 0 1;
	setAttr ".s" -type "double3" 35.000001907348633 35.000001907348633 35.000001907348633 ;
	setAttr ".ps" 0.20000000298023224;
	setAttr ".dl" yes;
createNode polyTweak -n "polyTweak1";
	rename -uid "B65F1C47-4A5D-0890-99FC-F2AF30874B40";
	setAttr ".uopa" yes;
	setAttr -s 296 ".tk";
	setAttr ".tk[97]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[98]" -type "float3" 0 0.15456969 0 ;
	setAttr ".tk[99]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[127]" -type "float3" 0 0.30777878 0 ;
	setAttr ".tk[128]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[129]" -type "float3" 0 1.8435663 0 ;
	setAttr ".tk[130]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[131]" -type "float3" 0 0.30777878 0 ;
	setAttr ".tk[147]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[148]" -type "float3" 0 0.11512887 0 ;
	setAttr ".tk[149]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[157]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[158]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[159]" -type "float3" 0 3.3540637 0 ;
	setAttr ".tk[160]" -type "float3" 0 4.3187542 0 ;
	setAttr ".tk[161]" -type "float3" 0 3.3540637 0 ;
	setAttr ".tk[162]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[163]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[177]" -type "float3" 0 0.22298071 0 ;
	setAttr ".tk[178]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[179]" -type "float3" 0 1.1210093 0 ;
	setAttr ".tk[180]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[181]" -type "float3" 0 0.22298071 0 ;
	setAttr ".tk[188]" -type "float3" 0 0.15456969 0 ;
	setAttr ".tk[189]" -type "float3" 0 1.8435663 0 ;
	setAttr ".tk[190]" -type "float3" 0 4.3187542 0 ;
	setAttr ".tk[191]" -type "float3" 0 5.4039092 0 ;
	setAttr ".tk[192]" -type "float3" 0 4.3187542 0 ;
	setAttr ".tk[193]" -type "float3" 0 1.8435663 0 ;
	setAttr ".tk[194]" -type "float3" 0 0.15456969 0 ;
	setAttr ".tk[207]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[208]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[209]" -type "float3" 0 1.9231035 0 ;
	setAttr ".tk[210]" -type "float3" 0 2.433192 0 ;
	setAttr ".tk[211]" -type "float3" 0 1.9231035 0 ;
	setAttr ".tk[212]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[213]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[219]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[220]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[221]" -type "float3" 0 3.3540637 0 ;
	setAttr ".tk[222]" -type "float3" 0 4.3187542 0 ;
	setAttr ".tk[223]" -type "float3" 0 3.3540637 0 ;
	setAttr ".tk[224]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[225]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[238]" -type "float3" 0 0.11512887 0 ;
	setAttr ".tk[239]" -type "float3" 0 1.1210093 0 ;
	setAttr ".tk[240]" -type "float3" 0 2.433192 0 ;
	setAttr ".tk[241]" -type "float3" 0 3.0249243 0 ;
	setAttr ".tk[242]" -type "float3" 0 2.433192 0 ;
	setAttr ".tk[243]" -type "float3" 0 1.1210093 0 ;
	setAttr ".tk[244]" -type "float3" 0 0.11512887 0 ;
	setAttr ".tk[251]" -type "float3" 0 0.30777878 0 ;
	setAttr ".tk[252]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[253]" -type "float3" 0 1.8435663 0 ;
	setAttr ".tk[254]" -type "float3" 0 1.2927567 0 ;
	setAttr ".tk[255]" -type "float3" 0 0.30777878 0 ;
	setAttr ".tk[269]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[270]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[271]" -type "float3" 0 1.9231035 0 ;
	setAttr ".tk[272]" -type "float3" 0 2.433192 0 ;
	setAttr ".tk[273]" -type "float3" 0 1.9231035 0 ;
	setAttr ".tk[274]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[275]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[283]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[284]" -type "float3" 0 0.15456969 0 ;
	setAttr ".tk[285]" -type "float3" 0 0.060149431 0 ;
	setAttr ".tk[301]" -type "float3" 0 0.22298071 0 ;
	setAttr ".tk[302]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[303]" -type "float3" 0 1.1210093 0 ;
	setAttr ".tk[304]" -type "float3" 0 0.81657791 0 ;
	setAttr ".tk[305]" -type "float3" 0 0.22298071 0 ;
	setAttr ".tk[333]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[334]" -type "float3" 0 0.11512887 0 ;
	setAttr ".tk[335]" -type "float3" 0 0.044801429 0 ;
	setAttr ".tk[705]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[706]" -type "float3" 0 0.2192595 0 ;
	setAttr ".tk[707]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[717]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[718]" -type "float3" 0 0.10764731 0 ;
	setAttr ".tk[719]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[735]" -type "float3" 0 0.42465925 0 ;
	setAttr ".tk[736]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[737]" -type "float3" 0 2.1349258 0 ;
	setAttr ".tk[738]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[739]" -type "float3" 0 0.42465925 0 ;
	setAttr ".tk[747]" -type "float3" 0 0.2084901 0 ;
	setAttr ".tk[748]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[749]" -type "float3" 0 1.0481597 0 ;
	setAttr ".tk[750]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[751]" -type "float3" 0 0.2084901 0 ;
	setAttr ".tk[765]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[766]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[767]" -type "float3" 0 3.6624906 0 ;
	setAttr ".tk[768]" -type "float3" 0 4.6339402 0 ;
	setAttr ".tk[769]" -type "float3" 0 3.6624906 0 ;
	setAttr ".tk[770]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[771]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[777]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[778]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[779]" -type "float3" 0 1.798131 0 ;
	setAttr ".tk[780]" -type "float3" 0 2.2750721 0 ;
	setAttr ".tk[781]" -type "float3" 0 1.798131 0 ;
	setAttr ".tk[782]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[783]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[796]" -type "float3" 0 0.2192595 0 ;
	setAttr ".tk[797]" -type "float3" 0 2.1349258 0 ;
	setAttr ".tk[798]" -type "float3" 0 4.6339402 0 ;
	setAttr ".tk[799]" -type "float3" 0 5.760879 0 ;
	setAttr ".tk[800]" -type "float3" 0 4.6339402 0 ;
	setAttr ".tk[801]" -type "float3" 0 2.1349258 0 ;
	setAttr ".tk[802]" -type "float3" 0 0.2192595 0 ;
	setAttr ".tk[808]" -type "float3" 0 0.10764731 0 ;
	setAttr ".tk[809]" -type "float3" 0 1.0481597 0 ;
	setAttr ".tk[810]" -type "float3" 0 2.2750721 0 ;
	setAttr ".tk[811]" -type "float3" 0 2.8283525 0 ;
	setAttr ".tk[812]" -type "float3" 0 2.2750721 0 ;
	setAttr ".tk[813]" -type "float3" 0 1.0481597 0 ;
	setAttr ".tk[814]" -type "float3" 0 0.10764731 0 ;
	setAttr ".tk[827]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[828]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[829]" -type "float3" 0 3.6624906 0 ;
	setAttr ".tk[830]" -type "float3" 0 4.6339402 0 ;
	setAttr ".tk[831]" -type "float3" 0 3.6624906 0 ;
	setAttr ".tk[832]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[833]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[839]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[840]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[841]" -type "float3" 0 1.798131 0 ;
	setAttr ".tk[842]" -type "float3" 0 2.2750721 0 ;
	setAttr ".tk[843]" -type "float3" 0 1.798131 0 ;
	setAttr ".tk[844]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[845]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[859]" -type "float3" 0 0.42465925 0 ;
	setAttr ".tk[860]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[861]" -type "float3" 0 2.1349258 0 ;
	setAttr ".tk[862]" -type "float3" 0 1.5551478 0 ;
	setAttr ".tk[863]" -type "float3" 0 0.42465925 0 ;
	setAttr ".tk[871]" -type "float3" 0 0.2084901 0 ;
	setAttr ".tk[872]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[873]" -type "float3" 0 1.0481597 0 ;
	setAttr ".tk[874]" -type "float3" 0 0.76351309 0 ;
	setAttr ".tk[875]" -type "float3" 0 0.2084901 0 ;
	setAttr ".tk[891]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[892]" -type "float3" 0 0.2192595 0 ;
	setAttr ".tk[893]" -type "float3" 0 0.085322879 0 ;
	setAttr ".tk[903]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[904]" -type "float3" 0 0.10764731 0 ;
	setAttr ".tk[905]" -type "float3" 0 0.041889999 0 ;
	setAttr ".tk[1058]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1059]" -type "float3" 0 0.093055263 0 ;
	setAttr ".tk[1060]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1088]" -type "float3" 0 0.18715806 0 ;
	setAttr ".tk[1089]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1090]" -type "float3" 0 0.99166632 0 ;
	setAttr ".tk[1091]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1092]" -type "float3" 0 0.18715806 0 ;
	setAttr ".tk[1108]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1109]" -type "float3" 0 0.18953793 0 ;
	setAttr ".tk[1110]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1118]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1119]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1120]" -type "float3" 0 1.7183185 0 ;
	setAttr ".tk[1121]" -type "float3" 0 2.1819422 0 ;
	setAttr ".tk[1122]" -type "float3" 0 1.7183185 0 ;
	setAttr ".tk[1123]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1124]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1138]" -type "float3" 0 0.38120958 0 ;
	setAttr ".tk[1139]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1140]" -type "float3" 0 2.0198576 0 ;
	setAttr ".tk[1141]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1142]" -type "float3" 0 0.38120958 0 ;
	setAttr ".tk[1149]" -type "float3" 0 0.093055263 0 ;
	setAttr ".tk[1150]" -type "float3" 0 0.99166632 0 ;
	setAttr ".tk[1151]" -type "float3" 0 2.1819422 0 ;
	setAttr ".tk[1152]" -type "float3" 0 2.7207046 0 ;
	setAttr ".tk[1153]" -type "float3" 0 2.1819422 0 ;
	setAttr ".tk[1154]" -type "float3" 0 0.99166632 0 ;
	setAttr ".tk[1155]" -type "float3" 0 0.093055263 0 ;
	setAttr ".tk[1168]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1169]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1170]" -type "float3" 0 3.4999256 0 ;
	setAttr ".tk[1171]" -type "float3" 0 4.4442511 0 ;
	setAttr ".tk[1172]" -type "float3" 0 3.4999256 0 ;
	setAttr ".tk[1173]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1174]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1180]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1181]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1182]" -type "float3" 0 1.7183185 0 ;
	setAttr ".tk[1183]" -type "float3" 0 2.1819422 0 ;
	setAttr ".tk[1184]" -type "float3" 0 1.7183185 0 ;
	setAttr ".tk[1185]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1186]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1199]" -type "float3" 0 0.18953793 0 ;
	setAttr ".tk[1200]" -type "float3" 0 2.0198576 0 ;
	setAttr ".tk[1201]" -type "float3" 0 4.4442511 0 ;
	setAttr ".tk[1202]" -type "float3" 0 5.5416188 0 ;
	setAttr ".tk[1203]" -type "float3" 0 4.4442511 0 ;
	setAttr ".tk[1204]" -type "float3" 0 2.0198576 0 ;
	setAttr ".tk[1205]" -type "float3" 0 0.18953793 0 ;
	setAttr ".tk[1212]" -type "float3" 0 0.18715806 0 ;
	setAttr ".tk[1213]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1214]" -type "float3" 0 0.99166632 0 ;
	setAttr ".tk[1215]" -type "float3" 0 0.71715194 0 ;
	setAttr ".tk[1216]" -type "float3" 0 0.18715806 0 ;
	setAttr ".tk[1230]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1231]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1232]" -type "float3" 0 3.4999256 0 ;
	setAttr ".tk[1233]" -type "float3" 0 4.4442511 0 ;
	setAttr ".tk[1234]" -type "float3" 0 3.4999256 0 ;
	setAttr ".tk[1235]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1236]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1244]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1245]" -type "float3" 0 0.093055263 0 ;
	setAttr ".tk[1246]" -type "float3" 0 0.033322774 0 ;
	setAttr ".tk[1262]" -type "float3" 0 0.38120958 0 ;
	setAttr ".tk[1263]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1264]" -type "float3" 0 2.0198576 0 ;
	setAttr ".tk[1265]" -type "float3" 0 1.460718 0 ;
	setAttr ".tk[1266]" -type "float3" 0 0.38120958 0 ;
	setAttr ".tk[1294]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1295]" -type "float3" 0 0.18953793 0 ;
	setAttr ".tk[1296]" -type "float3" 0 0.067872919 0 ;
	setAttr ".tk[1666]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1667]" -type "float3" 0 0.099522665 0 ;
	setAttr ".tk[1668]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1678]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1679]" -type "float3" 0 0.13361709 0 ;
	setAttr ".tk[1680]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1696]" -type "float3" 0 0.20016591 0 ;
	setAttr ".tk[1697]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1698]" -type "float3" 0 1.0605879 0 ;
	setAttr ".tk[1699]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1700]" -type "float3" 0 0.20016591 0 ;
	setAttr ".tk[1708]" -type "float3" 0 0.26873845 0 ;
	setAttr ".tk[1709]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1710]" -type "float3" 0 1.6363349 0 ;
	setAttr ".tk[1711]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1712]" -type "float3" 0 0.26873845 0 ;
	setAttr ".tk[1726]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1727]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1728]" -type "float3" 0 1.8377445 0 ;
	setAttr ".tk[1729]" -type "float3" 0 2.3335919 0 ;
	setAttr ".tk[1730]" -type "float3" 0 1.8377445 0 ;
	setAttr ".tk[1731]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1732]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1738]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1739]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1740]" -type "float3" 0 3.0867114 0 ;
	setAttr ".tk[1741]" -type "float3" 0 4.0547252 0 ;
	setAttr ".tk[1742]" -type "float3" 0 3.0867114 0 ;
	setAttr ".tk[1743]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1744]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1757]" -type "float3" 0 0.099522665 0 ;
	setAttr ".tk[1758]" -type "float3" 0 1.0605879 0 ;
	setAttr ".tk[1759]" -type "float3" 0 2.3335919 0 ;
	setAttr ".tk[1760]" -type "float3" 0 2.9097986 0 ;
	setAttr ".tk[1761]" -type "float3" 0 2.3335919 0 ;
	setAttr ".tk[1762]" -type "float3" 0 1.0605879 0 ;
	setAttr ".tk[1763]" -type "float3" 0 0.099522665 0 ;
	setAttr ".tk[1769]" -type "float3" 0 0.13361709 0 ;
	setAttr ".tk[1770]" -type "float3" 0 1.6363349 0 ;
	setAttr ".tk[1771]" -type "float3" 0 4.0547252 0 ;
	setAttr ".tk[1772]" -type "float3" 0 5.1815081 0 ;
	setAttr ".tk[1773]" -type "float3" 0 4.0547252 0 ;
	setAttr ".tk[1774]" -type "float3" 0 1.6363349 0 ;
	setAttr ".tk[1775]" -type "float3" 0 0.13361709 0 ;
	setAttr ".tk[1788]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1789]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1790]" -type "float3" 0 1.8377445 0 ;
	setAttr ".tk[1791]" -type "float3" 0 2.3335919 0 ;
	setAttr ".tk[1792]" -type "float3" 0 1.8377445 0 ;
	setAttr ".tk[1793]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1794]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1800]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1801]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1802]" -type "float3" 0 3.0867114 0 ;
	setAttr ".tk[1803]" -type "float3" 0 4.0547252 0 ;
	setAttr ".tk[1804]" -type "float3" 0 3.0867114 0 ;
	setAttr ".tk[1805]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1806]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1820]" -type "float3" 0 0.20016591 0 ;
	setAttr ".tk[1821]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1822]" -type "float3" 0 1.0605879 0 ;
	setAttr ".tk[1823]" -type "float3" 0 0.76699501 0 ;
	setAttr ".tk[1824]" -type "float3" 0 0.20016591 0 ;
	setAttr ".tk[1832]" -type "float3" 0 0.26873845 0 ;
	setAttr ".tk[1833]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1834]" -type "float3" 0 1.6363349 0 ;
	setAttr ".tk[1835]" -type "float3" 0 1.1295729 0 ;
	setAttr ".tk[1836]" -type "float3" 0 0.26873845 0 ;
	setAttr ".tk[1852]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1853]" -type "float3" 0 0.099522665 0 ;
	setAttr ".tk[1854]" -type "float3" 0 0.035638787 0 ;
	setAttr ".tk[1864]" -type "float3" 0 0.047847848 0 ;
	setAttr ".tk[1865]" -type "float3" 0 0.13361709 0 ;
	setAttr ".tk[1866]" -type "float3" 0 0.047847848 0 ;
createNode polyAutoProj -n "polyAutoProj2";
	rename -uid "4F2A0DD7-4549-8C6A-64ED-61B36105885A";
	setAttr ".cch" yes;
	setAttr ".uopa" yes;
	setAttr ".ics" -type "componentList" 1 "f[0:1919]";
	setAttr ".ix" -type "matrix" 1 0 0 0 0 0.5 0 0 0 0 1 0 0 0 0 1;
	setAttr ".s" -type "double3" 35.000001907348633 35.000001907348633 35.000001907348633 ;
	setAttr ".ps" 0.20000000298023224;
	setAttr ".dl" yes;
createNode polyAutoProj -n "polyAutoProj3";
	rename -uid "42B730D0-466F-BBAB-ADA9-F79E7677D225";
	setAttr ".cch" yes;
	setAttr ".uopa" yes;
	setAttr ".ics" -type "componentList" 1 "f[0:1919]";
	setAttr ".ix" -type "matrix" 1 0 0 0 0 0.5 0 0 0 0 1 0 0 0 0 1;
	setAttr ".s" -type "double3" 35.000001907348633 35.000001907348633 35.000001907348633 ;
	setAttr ".ps" 0.20000000298023224;
	setAttr ".dl" yes;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 1;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 6 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :openPBR_shader1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :initialMaterialInfo;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".ren" -type "string" "arnold";
	setAttr ".dss" -type "string" "openPBR_shader1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "polyAutoProj3.out" "GrassyHillTerrainShape.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "polyTweak1.out" "polyAutoProj1.ip";
connectAttr "GrassyHillTerrainShape.wm" "polyAutoProj1.mp";
connectAttr "polyCube1.out" "polyTweak1.ip";
connectAttr "polyAutoProj1.out" "polyAutoProj2.ip";
connectAttr "GrassyHillTerrainShape.wm" "polyAutoProj2.mp";
connectAttr "polyAutoProj2.out" "polyAutoProj3.ip";
connectAttr "GrassyHillTerrainShape.wm" "polyAutoProj3.mp";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "GrassyHillTerrainShape.iog" ":initialShadingGroup.dsm" -na;
// End of Huntsman_Asset5.ma
